package com.example.route

val allstops= listOf<Stop>(Stop(1,"Tughlakabad",1.2f),
    Stop(2,"Mohan Estate",1.3f),
    Stop(3,"Sarita Vihar",0.7f),
    Stop(4,"Jasola-Appolo",0.9f),
    Stop(5,"Harkesh Nagar",1.1f),
    Stop(6,"Govindpuri",1.2f),
    Stop(7,"Kalkaji Mandir",1.4f),
    Stop(8,"Nehru Place",0.8f),
    Stop(9,"Kailash Colony",1.4f),
    Stop(10,"Moolchand",1.3f))

val totalstops= listOf<Stop>(Stop(1,"Tughlakabad",1.2f),
    Stop(2,"Mohan Estate",1.3f),
    Stop(3,"Sarita Vihar",0.7f),
    Stop(4,"Jasola-Appolo",0.9f),
    Stop(5,"Harkesh Nagar",1.1f),
    Stop(6,"Govindpuri",1.2f),
    Stop(7,"Kalkaji Mandir",1.4f),
    Stop(8,"Nehru Place",0.8f),
    Stop(9,"Kailash Colony",1.4f),
    Stop(10,"Moolchand",1.3f),
    Stop(11,"Lajpat nagar",1.1f),
    Stop(12,"Jangpura",0.7f),
    Stop(13,"JLN Stadium",0.9f),
    Stop(14,"Khan Market",1.1f),
    Stop(15,"Central Secretariat",1.7f),
    Stop(16,"Janpath",0.3f),
    Stop(17,"Mandi House",1.3f),
    Stop(18,"ITO",1.1f),
    Stop(19,"Delhi Gate",0.2f),
    Stop(20,"Jama Masjid",1.3f),
    Stop(21,"Lal Quila",0.9f),
    Stop(22,"Kashmere Gate",1.1f))